# Generated by Django 3.1.4 on 2023-05-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cod_item', models.IntegerField(blank=True, null=True, unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
