# Generated by Django 3.1.4 on 2023-05-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id_consumidor', models.AutoField(primary_key=True, serialize=False)),
                ('id_pessoa', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
