# Generated by Django 3.1.4 on 2023-05-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEmprestimo',
            fields=[
                ('id_histemp', models.AutoField(db_column='id_histEmp', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('id_consumidor', models.ForeignKey(blank=True, db_column='id_consumidor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.consumidor')),
                ('id_funcionario', models.ForeignKey(blank=True, db_column='id_funcionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.funcionario')),
                ('id_item', models.ForeignKey(blank=True, db_column='id_item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.item')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoConsumo',
            fields=[
                ('id_histcons', models.AutoField(db_column='id_histCons', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('id_consumidor', models.ForeignKey(blank=True, db_column='id_consumidor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.consumidor')),
                ('id_funcionario', models.ForeignKey(blank=True, db_column='id_funcionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.funcionario')),
                ('id_item', models.ForeignKey(blank=True, db_column='id_item', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.item')),
            ],
        ),
    ]
