# Generated by Django 3.1.4 on 2023-06-23 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_consumidor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoemprestimo',
            name='id_consumidor',
            field=models.ForeignKey(blank=True, db_column='id_pessoa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.consumidor'),
        ),
    ]
