# Generated by Django 3.1.4 on 2023-06-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20230623_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoemprestimo',
            name='id_funcionario',
        ),
    ]
